# Kubernetes Secret Manifest
# This stores sensitive configuration data, like API keys or passwords.
# Data is stored base64 encoded, NOT encrypted by default. Access control is key.
# Think of this as a classified S.H.I.E.L.D. file with restricted access.
apiVersion: v1 # API version for Secrets
kind: Secret # Type of object
metadata:
  name: hero-registry-secret # Name of the Secret
  # namespace: default # Optional: specify namespace if not default
type: Opaque # Default type for arbitrary user-defined data. Other types exist (e.g., kubernetes.io/tls).
data:
  # Data values MUST be base64 encoded.
  # You can encode strings using: echo -n 'your-secret-value' | base64
  # Example: echo -n 's3cr3t-ap1-k3y' | base64  => czNjcmV0LWFwMS1rM3k=

  # Key: API_KEY
  # Value: 's3cr3t-ap1-k3y' (base64 encoded)
  API_KEY: czNjcmV0LWFwMS1rM3k=

  # Key: DATABASE_PASSWORD
  # Value: 'p@sswOrd!' (base64 encoded) => cEBzc3dvUmQh
  DATABASE_PASSWORD: cEBzc3dvUmQh

  # Add other sensitive key-value pairs here, ensuring values are base64 encoded.
